# Project: test
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"F:/Code/Tools/DevCPP_x64_Por/MinGW64/lib" -L"F:/Code/Tools/DevCPP_x64_Por/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pg -g3
INCS     = -I"F:/Code/Tools/DevCPP_x64_Por/MinGW64/include" -I"F:/Code/Tools/DevCPP_x64_Por/MinGW64/x86_64-w64-mingw32/include" -I"F:/Code/Tools/DevCPP_x64_Por/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"F:/Code/Tools/DevCPP_x64_Por/MinGW64/include" -I"F:/Code/Tools/DevCPP_x64_Por/MinGW64/x86_64-w64-mingw32/include" -I"F:/Code/Tools/DevCPP_x64_Por/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"F:/Code/Tools/DevCPP_x64_Por/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = test.exe
CXXFLAGS = $(CXXINCS) -pg -g3
CFLAGS   = $(INCS) -pg -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
